server:
  port: 8600
  max-http-header-size: 102400
  compression:
    enabled: true
    min-response-size: 20480  #20K 以上开启gzip
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${STARCOIN_MYSQL_URL}
    username: ${STARCOIN_MYSQL_USER}
    password: ${STARCOIN_MYSQL_PWD}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 不配置默认与maximum-pool-size相同
      minimum-idle: 5 #minimum number of idle connections maintained by HikariCP in a connection pool
      # 连接池最大连接数，默认是10
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      idle-timeout: 500000 #maximum idle time for connection
      connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
      max-lifetime: 1800000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.

  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create # 开发阶段使用
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

jasypt:
  encryptor:
    bean: encryptorBean
    password: ${STARCOIN_ES_PWD}

#elasticsearch:
#  host: ${STARCOIN_ES_URL}
#  protocol: ${STARCOIN_ES_PROTOCOL}
#  port: ${STARCOIN_ES_PORT}
#  username: ${STARCOIN_ES_USER}
#  connTimeout: 10000
#  socketTimeout: 10000
#  connectionRequestTimeout: 2000

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
      # 输出数据库模型（开发阶段）
      hibernate:
        tool:
          hbm2ddl: DEBUG

